src/style/Home.css

Change login button

---

src/components/headerfooter/Footer.jsx
src/components/headerfooter/Header.jsx
src/style/Headerfooter.css
src/style/Home.css

created Headerfooter.css 
modified code in Footer.jsx 
center aligned content on navbar

minor-ui-fixes

---

src/components/auth/LogIn.jsx
src/components/auth/SignUp.jsx
src/pages/Home.jsx
src/style/LogIn.css
src/style/SignUp.css

changed login , signup form dimensions

fixed sign up to only appear at the time of patient login

---

src/components/PrivateRoute.jsx
src/components/auth/SignUp.jsx
src/pages/MainComponent.jsx

Now nobady can see dashboard without logging in.
when sign up is successful user gets redirected to dashboard

Private Routes setup

---

package-lock.json
package.json
src/components/headerfooter/Header.jsx
src/pages/DashBoard.jsx
src/style/Headerfooter.css

* Changed the location of the signout button from the dashboard to the nav bar
* Added react-icon to use icons

changed the location of signout button

---

src/components/SideBar.jsx
src/components/auth/SignUp.jsx
src/lib/init-firebase.js
src/pages/DashBoard.jsx
src/pages/Home.jsx
src/pages/MainComponent.jsx
src/style/SideBar.css

* Signup now takes name as well
* Signup shows error given by firestore

Dash board

---

src/components/auth/LogIn.jsx
src/components/auth/SignUp.jsx
src/pages/DashBoard.jsx

Now the username is displayed in the dashboard

now the username is displayed in the dashboard

---

src/components/auth/LogIn.jsx

error handling on the error page

---

src/components/SideBar.jsx
src/components/headerfooter/Header.jsx
src/lib/init-firebase.js
src/pages/Home.jsx
src/style/SideBar.css

profile photo of the user on the sidebar

profile photo of the user on the sidebar

---

src/components/SideBar.jsx

profile-photo-error-solved

---

src/components/SideBar.jsx

Whenever add photo button is clicked

Profile image is automatically updated

---

src/components/dashboard/UserDashboard.jsx
src/pages/DashBoard.jsx
src/style/UserDashboard.css

Created userdashboard

---

src/components/dashboard/HistoryCard.jsx
src/components/dashboard/MedicalHistory.jsx

User dashboard

---

src/components/SideBar.jsx

Added user id to the sidebar

---

src/components/SideBar.jsx
src/components/dashboard/Appointments.jsx
src/components/dashboard/HealthArticle.jsx
src/pages/MainComponent.jsx
src/pages/MakeAppointments.jsx
src/pages/Profile.jsx
src/style/dashboard/Profile.css

* Fixed routing errors for the `appointment` and `profile` components.
* Implemented profile component.
* Changed appointment page to makeAppoinment to avoid naming conflict with appointment component

User profile

---

src/components/dashboard/Doctor/DoctorDashBoard/AddMedicalHistory.jsx
src/components/dashboard/Doctor/DoctorDashBoard/DoctorDashboard.jsx

Doctor dashboard added

---

src/components/auth/LogIn.jsx
src/components/auth/SignUp.jsx
src/components/dashboard/AddMedicalHistory.jsx
src/components/dashboard/HistoryCard.jsx
src/components/dashboard/ShowMedicalHistory.jsx
src/pages/DoctorDashboard.jsx
src/pages/Home.jsx

Doctor dashboard

---

src/pages/Profile.jsx

* Two-factor-auth
* Profile backend

Profile backend fixed

---

src/components/dashboard/Appointments.jsx
src/components/dashboard/HealthArticle.jsx
src/components/dashboard/MedicalHistory.jsx
src/components/dashboard/NearbyHospitals.jsx
src/components/dashboard/UserDashboard.jsx
src/style/dashboard/Appointments.css
src/style/dashboard/MedicalHistory.css
src/style/dashboard/UserDashboard.css

**Pull Request Format**
**Description**
Provide a brief summary of the changes introduced by the pull request.
**Related Issue**
Include the issue number or a brief description of the related issue, if applicable.
**Changes Made**
Describe the changes made in the pull request in a clear and concise manner.
**Checklist**

UI upgrade

---

src/components/dashboard/HealthArticle.jsx

**Pull Request Format**
**Description**
Provide a brief summary of the changes introduced by the pull request.
**Related Issue**
Include the issue number or a brief description of the related issue, if applicable.
**Changes Made**
Describe the changes made in the pull request in a clear and concise manner.
**Checklist**

slice error fixed
